# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Production

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'public/**'

  # Allow triggering manually.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch the Docsy theme
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Build
        run: |
          color='#AFE1AF'
          version=' &middot; <a href="https://github.com/${{ github.repository }}/tree/${{ github.sha }}">${{ github.sha }}</a>'
          sed -i 's/#fff/$color/' $(find ./public -type f)
          sed -i 's/#fff/$version/' $(find ./public -type f)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Do not delete previews on each production deploy.
          keep_files: true
          commit_message: ${{ github.event.head_commit.message }}